FROM jboss/keycloak:8.0.1

COPY api-key-module/target/api-key-module-0.1.jar /opt/jboss/keycloak/standalone/deployments
COPY example/keycloak-metrics-spi-1.0.4.jar /opt/jboss/keycloak/standalone/deployments
